import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'secondary-container': '#fecb97',
        'secondary-fixed-dim': '#efbd8a',
        'secondary-fixed': '#ffdcbc',
        surface: '#f9faf5',
        'on-primary': '#ffffff',
        'on-surface-variant': '#414942',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#79542a',
        'primary-container': '#1b4d2e',
        'surface-container-highest': '#e1e3de',
        'outline-variant': '#c1c9bf',
        'on-primary-fixed': '#00210e',
        'surface-tint': '#376847',
        'error-container': '#ffdad6',
        tertiary: '#45260f',
        'on-primary-fixed-variant': '#1e5031',
        'inverse-surface': '#2e312e',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#9ed3aa',
        'on-tertiary-fixed-variant': '#623f25',
        'tertiary-fixed-dim': '#efbc9b',
        'inverse-on-surface': '#f0f1ec',
        'primary-fixed': '#b9efc5',
        primary: '#00361a',
        'surface-bright': '#f9faf5',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#9ed3aa',
        'on-background': '#191c19',
        'on-secondary-fixed': '#2c1700',
        'on-tertiary-fixed': '#2f1502',
        background: '#f9faf5',
        'tertiary-container': '#5e3c23',
        'surface-container-high': '#e7e9e4',
        'surface-container': '#edeee9',
        error: '#ba1a1a',
        'surface-variant': '#e1e3de',
        outline: '#717971',
        'tertiary-fixed': '#ffdcc6',
        'surface-dim': '#d9dbd6',
        'on-primary-container': '#89bd95',
        'on-secondary-fixed-variant': '#614018',
        'surface-container-low': '#f3f4ef',
        secondary: '#7c572d',
        'on-tertiary-container': '#d7a787',
        'on-surface': '#191c19',
        'amber-gold': '#D4A574',
        'soft-cream': '#F5F0E8',
        'rich-wood': '#5C3A21',
        'ivory-tile': '#FFFFF0',
        'navy-pip': '#000080',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '16px',
        'margin-mobile': '20px',
        unit: '8px',
        'margin-desktop': '40px',
        'piece-gap': '4px',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};

export default config;
